[general]
import = [
  "/usr/lib/node_modules/alacritty-themes/themes/Gruvbox-Dark.toml"
]

[colors.primary]
# background = "#0d0e0f"
background = "#181d1c"
foreground = "#d4be98"

[font]
size = 11

[font.bold]
family = "MonaspiceRn Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "MonaspiceRn Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "MonaspiceRn Nerd Font Mono"
style = "Italic"

[font.normal]
family = "MonaspiceRn Nerd Font Mono"
style = "Bold"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"

[scrolling]
history = 50_000

[window]
opacity = 0.90

[[keyboard.bindings]]
key = ";"
mods = "Control"
chars = "$HOME/.scripts/tmux-sessionizer.sh\r"
